backend:
  name: github
  repo: danniskhaq-ui/Web-portofolio
  branch: main
  base_url: https://gateway.decapbridge.com
  site_domain: web-portofolio-wildan.vercel.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
